version: '3.5'

services:
  mkdown:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mkdown
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer-mkdown:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
